// <auto-generated />
using System;
using EdiProcessor.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EdiProcessor.Infrastructure.Migrations
{
    [DbContext(typeof(EdiDbContext))]
    partial class EdiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("EdiProcessor.Core.Models.TradingPartner", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<string>("InterchangeId").IsRequired().HasMaxLength(15).HasColumnType("TEXT");
                b.Property<string>("InterchangeQualifier").IsRequired().HasMaxLength(2).HasColumnType("TEXT");
                b.Property<bool>("IsActive").HasColumnType("INTEGER");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("InterchangeId");
                b.ToTable("TradingPartners");
                b.HasData(
                    new { Id = 1, Name = "Blue Cross Blue Shield", InterchangeId = "BCBS001", InterchangeQualifier = "ZZ", IsActive = true, CreatedAt = new DateTime(2024, 1, 1) },
                    new { Id = 2, Name = "Aetna Health", InterchangeId = "AETNA01", InterchangeQualifier = "ZZ", IsActive = true, CreatedAt = new DateTime(2024, 1, 1) },
                    new { Id = 3, Name = "UnitedHealthcare", InterchangeId = "UHC0001", InterchangeQualifier = "ZZ", IsActive = true, CreatedAt = new DateTime(2024, 1, 1) }
                );
            });

            modelBuilder.Entity("EdiProcessor.Core.Models.EdiTransaction", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("ControlNumber").IsRequired().HasMaxLength(9).HasColumnType("TEXT");
                b.Property<string>("ErrorDescription").HasColumnType("TEXT");
                b.Property<string>("RawContent").IsRequired().HasColumnType("TEXT");
                b.Property<DateTime>("ReceivedAt").HasColumnType("TEXT");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
                b.Property<int>("TradingPartnerId").HasColumnType("INTEGER");
                b.Property<string>("TransactionType").IsRequired().HasMaxLength(10).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("ControlNumber");
                b.HasIndex("ReceivedAt");
                b.HasIndex("TradingPartnerId");
                b.ToTable("EdiTransactions");
            });

            modelBuilder.Entity("EdiProcessor.Core.Models.Claim837", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("ClaimNumber").IsRequired().HasMaxLength(38).HasColumnType("TEXT");
                b.Property<string>("ClaimType").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<int>("EdiTransactionId").HasColumnType("INTEGER");
                b.Property<string>("PatientControlNumber").IsRequired().HasColumnType("TEXT");
                b.Property<string>("PatientName").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("PayerId").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
                b.Property<string>("PayerName").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("ProviderId").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
                b.Property<string>("ProviderName").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("RejectionReason").HasColumnType("TEXT");
                b.Property<DateTime>("ServiceDateFrom").HasColumnType("TEXT");
                b.Property<DateTime?>("ServiceDateTo").HasColumnType("TEXT");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
                b.Property<decimal>("TotalAmount").HasPrecision(12, 2).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("CreatedAt");
                b.HasIndex("EdiTransactionId");
                b.HasIndex("Status");
                b.ToTable("Claims");
            });

            modelBuilder.Entity("EdiProcessor.Core.Models.ServiceLine", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<int>("Claim837Id").HasColumnType("INTEGER");
                b.Property<decimal>("ChargedAmount").HasPrecision(12, 2).HasColumnType("TEXT");
                b.Property<string>("DiagnosisPointers").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Modifier").HasMaxLength(10).HasColumnType("TEXT");
                b.Property<string>("ProcedureCode").IsRequired().HasMaxLength(10).HasColumnType("TEXT");
                b.Property<DateTime>("ServiceDate").HasColumnType("TEXT");
                b.Property<int>("Units").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("Claim837Id");
                b.ToTable("ServiceLines");
            });

            modelBuilder.Entity("EdiProcessor.Core.Models.AcknowledgmentRecord", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("AckType").IsRequired().HasMaxLength(5).HasColumnType("TEXT");
                b.Property<string>("AcknowledgmentCode").IsRequired().HasMaxLength(5).HasColumnType("TEXT");
                b.Property<string>("ControlNumber").IsRequired().HasMaxLength(9).HasColumnType("TEXT");
                b.Property<string>("Description").HasMaxLength(500).HasColumnType("TEXT");
                b.Property<int>("EdiTransactionId").HasColumnType("INTEGER");
                b.Property<string>("ErrorCode").HasColumnType("TEXT");
                b.Property<string>("FunctionalGroupControlNumber").HasColumnType("TEXT");
                b.Property<string>("NoteCode").HasMaxLength(10).HasColumnType("TEXT");
                b.Property<DateTime>("ReceivedAt").HasColumnType("TEXT");
                b.Property<string>("TransactionSetControlNumber").HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("EdiTransactionId");
                b.ToTable("Acknowledgments");
            });

            modelBuilder.Entity("EdiProcessor.Core.Models.FileProcessingLog", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<int>("ClaimsProcessed").HasColumnType("INTEGER");
                b.Property<DateTime?>("CompletedAt").HasColumnType("TEXT");
                b.Property<string>("DetectedType").HasMaxLength(20).HasColumnType("TEXT");
                b.Property<string>("ErrorMessage").HasColumnType("TEXT");
                b.Property<string>("FileName").IsRequired().HasMaxLength(260).HasColumnType("TEXT");
                b.Property<long>("FileSizeBytes").HasColumnType("INTEGER");
                b.Property<string>("FinalPath").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
                b.Property<string>("OriginalPath").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
                b.Property<DateTime>("PickedUpAt").HasColumnType("TEXT");
                b.Property<TimeSpan?>("ProcessingDuration").HasColumnType("TEXT");
                b.Property<string>("Source").IsRequired().HasMaxLength(30).HasColumnType("TEXT");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
                b.Property<string>("ControlNumber").HasMaxLength(20).HasColumnType("TEXT");
                b.Property<int?>("TradingPartnerId").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("PickedUpAt");
                b.HasIndex("Status");
                b.HasIndex("TradingPartnerId");
                b.ToTable("FileProcessingLogs");
            });
#pragma warning restore 612, 618
        }
    }
}
